name: Docker

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: setup Docker Build
      uses: docker/setup-buildx-action@v3.0.0

    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.1.1
      with:
        name: build_go
    
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: vinimeso
        password: ${{secrets.PASSWORD_DOCKER_HUB}}
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.0.0
      with:  
        context: .        
        file: ./Dockerfile
        push: true
        tags: vinimeso/go_ci:${{github.ref_name}}
